# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3f4d94035e4347f38badc938dab881dbba0afe41435d11ed0aa8c4d908e90319505fabafb530ecc55cfac1f975a55e7ca40f9401a642b9a45fb24f254d73f691

test:
  secret_key_base: d2db985cb2ac0ff12ebb2fd3a2bdefabab9726c24795842cc393858eee285220c4c1e96993f819dace4c22dfa891510e47c570a6cb11ea4432e98326a973d83b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
